from enum import Enum


class ErrorConstants(str, Enum):
    ACTIVE_CAMPAIGN_ALREADY_EXISTS_ERROR = 'ACTIVE_CAMPAIGN_ALREADY_EXISTS_ERROR',
    BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
    CAMPAIGN_NOT_FOUND_ERROR = 'CAMPAIGN_NOT_FOUND_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    INVALID_CAMPAIGN_STATUS_ERROR = 'INVALID_CAMPAIGN_STATUS_ERROR'
